name: Build & Artifact Workflow
on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          echo "Compiling project..."
          mkdir output
          echo "Sample artifact content" > output/artifact.txt

      - name: Upload Artifact with Retention
        uses: actions/upload-artifact@v4
        with:
          name: persistent-artifact
          path: output/artifact.txt
          retention-days: 30 

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          files: output/artifact.txt
