name: Build & Artifact Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          echo "Compiling project..."
          mkdir output
          echo "Sample artifact content" > output/artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/artifact.txt
