name: SECURE Secrets Demo
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use GitHub Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Will be masked
        run: |
          echo "SECURE KEY: ${{ secrets.API_KEY }}"
          # Simulate using the key
          echo "Pretending to call an API with key: ${{ secrets.API_KEY }}"
